### ISSUE TITLE
bug with Elevenlabs-TTS plugin

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio-Plugins#6]
Traceback (most recent call last):
  File "C:\ApplioV3.2.0\app.py", line 84, in <module>
    plugins_tab()
  File "C:\ApplioV3.2.0\tabs\plugins\plugins.py", line 31, in plugins_tab
    plugin_import = importlib.import_module(plugin_main)
  File "C:\ApplioV3.2.0\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\ApplioV3.2.0\tabs\plugins\installed\Elevenlabs-TTS\plugin.py", line 19, in <module>
    from rvc.infer.infer import VoiceConverter
ImportError: cannot import name 'VoiceConverter' from 'rvc.infer.infer' (C:\ApplioV3.2.0\rvc\infer\infer.py)

Для продолжения нажмите любую клавишу . . .

Applio doesn't work after plugin installed. Need to delete catalog C:\ApplioV3.2.0\tabs\plugins\installed\Elevenlabs-TTS, and after all work right. I downloaded last version Elevenlabs-TTS with last fix.

**Comment by aitronssesin** [comment]
Fixed https://github.com/IAHispano/Applio-Plugins/commit/90ceb1fe63c86ab226ccbd8c7037b8719575e202
