### ISSUE TITLE
bug ElevenLabs-TTS plugin in colab

### ISSUE THREAD

**Issue by mikhail2013ru** [IAHispano/Applio-Plugins#7]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "/content/program_ml/tabs/plugins/installed/Elevenlabs-TTS/plugin.py", line 168, in run_tts_script
    voice_converter.infer_pipeline(
AttributeError: 'VoiceConverter' object has no attribute 'infer_pipeline'

**Comment by blaisewf** [comment]
fixed
